Feat: 종 검색기능 추가
Petmunity/fe pull request #2
Opened 2023-12-05 07:04 UTC by Duck-98

## 개요

- 목데이터를 활용한 견종, 묘종 검색 기능
- 커스텀 모달
- 커스텀 디바운스
- 스타일 수정
## PR 유형

어떤 변경 사항이 있나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [x] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

2023-12-05 09:02 UTC, JhsK requested changes

2023-12-05 09:02 UTC, JhsK commented on src/components/common/Modal/Backdrop.tsx
> +      className={`${
인라인 `hidden`을 설정했는데 style에서도 hidden을 설정한 이유가 뭐야?

2023-12-05 09:02 UTC, JhsK commented on src/components/common/Modal/index.tsx
> +export default function Modal({
여기 코드 전제적으로 가독성이 너무 안좋아보이긴 해 삼항 연산자를 너무 사용하는 것 보다는 가능하면 if문으로 빼서 사용하는게 가독성이 더 좋을 것 같앙

```
if (typeof window === 'undefined') return <></<>;
```

식으로 처리하는 것 처럼?

2023-12-05 09:02 UTC, JhsK commented on src/components/common/Modal/index.tsx
> +export default function Modal({
아래 코드는 내가 회사에서 모달 만들었을 때 코드인데 참고해도 좋을 듯? 

```
import React, { useEffect, useState } from 'react';
import { ModalBackdrop } from 'ui';

import { createPortal } from 'react-dom';

import useModalStore from '../store/Modal';

const ModalPortal = () => {
  const [isClient, setIsClient] = useState(false);
  const [show, children] = useModalStore((state) => [
    state.show,
    state.children,
  ]);

  useEffect(() => {
    setIsClient(true);
  }, []);

  const renderBackdrop = () => {
    if (show) return <ModalBackdrop />;
    return <></>;
  };

  const renderModal = () => {
    if (show && children) {
      return children;
    }
    return <></>;
  };

  if (typeof window === 'undefined') return <></>;
  if (!isClient) return <></>;

  return (
    <>
      {createPortal(
        renderBackdrop(),
        document.getElementById('modal-backdrop') as HTMLElement,
      )}
      {createPortal(
        renderModal(),
        document.getElementById('modal') as HTMLElement,
      )}
    </>
  );
};

export default ModalPortal;
```

2023-12-05 09:02 UTC, JhsK commented on src/components/common/Modal/index.tsx
> +}: PropsWithChildren<any>) {
여기도 props를 인터페이스 선언해서 props로 받거나 any를 제대로 처리해주는게 좋을 것 같앙

2023-12-05 09:02 UTC, JhsK commented on src/components/common/Modal/index.tsx
> +            style={{ ...style, display: isOpen ? undefined : "none" }}
인라인 스타일을 쓴 이유가 있어?

2023-12-06 02:36 UTC, Duck-98 commented on src/components/common/Modal/Backdrop.tsx
> +      className={`${
뺀다는걸 깜빡함ㅋㅋ

2023-12-06 04:02 UTC, JhsK requested changes

2023-12-06 04:02 UTC, JhsK commented on src/app/petinfo/SearchBreed.tsx
> +          searchResult.map((breedItem: any) => (
any 타입은 최대한 안쓰는게 좋을듯?

2023-12-06 04:02 UTC, JhsK commented on src/app/petinfo/page.tsx
> +            <div>
리액트에서는 `id`를 잘 안쓰니깐 htmpFor, id를 쓰지 말고 label 태그를 하나로 묶어서 처리하는게 더 깔끔해보일듯? 이거는 개취라 너가 편한대루

2023-12-06 05:07 UTC, Duck-98 commented on src/components/common/Modal/index.tsx
> +export default function Modal({
수정했읍니다

2023-12-06 05:07 UTC, Duck-98 commented on src/components/common/Modal/index.tsx
> +}: PropsWithChildren<any>) {
수정했읍니다

2023-12-06 05:07 UTC, Duck-98 commented on src/components/common/Modal/index.tsx
> +            style={{ ...style, display: isOpen ? undefined : "none" }}
수정했읍니다

2023-12-06 05:07 UTC, Duck-98 commented on src/app/petinfo/SearchBreed.tsx
> +          searchResult.map((breedItem: any) => (
수정했읍니다

2023-12-07 00:08 UTC, JhsK requested changes

2023-12-07 00:08 UTC, JhsK commented on src/components/common/Modal/index.tsx
> +  return modalRoot
Modal을 사용할 때 Portal 없이 사용하는 경우도 있는거야? 그게 아니라면 modalRoot가 없을 떄 그냥 `children`을 리턴해주면 안될거 같아서

2023-12-07 00:26 UTC, Duck-98 commented on src/components/common/Modal/index.tsx
> +  return modalRoot
```ts
return modalRoot
    ? createPortal(
        <>
          <Backdrop isOpen={isOpen} onClick={onClose} />
          <div
            hidden={!isOpen}
            className={`fixed inset-0 top-56 z-50 mx-auto h-fit w-10/12 rounded-lg bg-white md:max-w-[375px] ${className}`}
          >
            {children}
          </div>
        </>,
        modalRoot,
      )
    : null;
}
```

지금 그래서 이런식으로 바뀌어있는데, modalRoot가 없을 때 children이 아니라 null 리턴으로 바꿨음

2023-12-08 13:39 UTC, JhsK commented
굳! 고생했으 approve하면 될 듯?

2023-12-09 15:48 UTC, merged